## Write a Numpy program to compute the multiplication of two given matrixes

In [1]:
import numpy as np 

In [76]:
a = [[1, 2], [3, 4]]
b = [[5, 6], [7, 8]]


z= np.dot(a, b )
z


array([[19, 22],
       [43, 50]])

## Write a NumPy program to compute the determinant of a given square array

In [59]:

a = np.array([[2, 3], [1, 2]])

print("Determinant of  array:")
np.linalg.det(a)


Determinant of  array:


1.0

## Write a NumPy program to compute the cross product of two given vectors

In [81]:
a = [[1, 2], [3, 4]]
b = [[5, 6], [7, 8]]
n=np.cross(a,b)

In [82]:
n

array([-4, -4])

## Write a NumPy program to compute the condition number of a given matrix

In [99]:
a = np.array([[1, 0, 1], [3, 1, 1], [2, 0, 3]])


np.linalg.cond(a)

39.72958014157715

## Write a NumPy program to compute the inverse of a given matrix

In [97]:
 np.linalg.inv(a)

array([[ 3.,  0., -1.],
       [-7.,  1.,  2.],
       [-2., -0.,  1.]])